changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking changes
    - title: Exciting New Features 🎉
      labels:
        - new features
    - title: Bug fix 🐛
      labels:
        - bug fix
    - title: Other Changes
      labels:
        - "*"
